# Generated by Django 4.2 on 2023-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="line2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
