# Generated by Django 4.2 on 2023-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_line2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="line2",
            field=models.CharField(default="harlow grove", max_length=100),
            preserve_default=False,
        ),
    ]
