# Generated by Django 4.2 on 2023-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_productset_product"),
        ("order", "0002_order_address_alter_order_products"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="products",
        ),
        migrations.AddField(
            model_name="order",
            name="productsets",
            field=models.ManyToManyField(
                blank=True, null=True, to="profiles.productset"
            ),
        ),
    ]
