# Generated by Django 4.2 on 2023-06-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
        ("profiles", "0004_alter_productset_product"),
        ("order", "0003_remove_order_products_order_productsets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="productsets",
            field=models.ManyToManyField(to="profiles.productset"),
        ),
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.profile"
            ),
        ),
    ]
