# Generated by Django 4.2 on 2023-06-10 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_productset_product"),
        ("address", "0003_alter_address_line2"),
        ("order", "0004_alter_order_address_alter_order_productsets_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
    ]
