# Generated by Django 4.2 on 2023-06-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_remove_productset_first_login_profile_first_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="productset",
            name="message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
