# Generated by Django 4.2 on 2023-05-31 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('profiles', '0003_alter_productset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
