# Generated by Django 4.2 on 2023-05-11 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_remove_product_images_image_product'),
        ('profiles', '0003_favourites_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourites',
            new_name='Cart',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='produts',
            new_name='products',
        ),
    ]
