# Generated by Django 4.2 on 2023-06-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_productset_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productset",
            name="message",
            field=models.BooleanField(default=False),
        ),
    ]
