# Generated by Django 4.2 on 2023-05-11 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_images_image_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_rename_favourites_cart_rename_produts_cart_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Wishlist',
        ),
    ]
