# Generated by Django 4.2 on 2023-06-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_productset_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="first_login",
        ),
    ]
