# Generated by Django 4.2 on 2023-06-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('thumbnail', models.CharField(max_length=100)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('OPPO', 'OPPO'), ('Huawei', 'Huawei'), ('Microsoft', 'Microsoft'), ('Infinix', 'Infinix'), ('HP', 'HP')], max_length=100)),
                ('category', models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop')], max_length=100)),
                ('rating', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('discount', models.FloatField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
