# Generated by Django 4.2 on 2023-05-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
    ]
