# Generated by Django 4.2 on 2023-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_image_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='store.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='store.product'),
        ),
    ]
