# Generated by Django 4.2 on 2023-05-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_profile_cart_remove_profile_favourites_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
