# Generated by Django 4.2 on 2023-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_images_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Smartphone', 'Smartphone'), ('Laptop', 'Laptop')], max_length=100),
        ),
    ]
